### ISSUE TITLE
After update on devices network error

### ISSUE THREAD

**Issue by EgidijusViko** [opengisch/qfieldcloud#956] opened 2024-05-30 07:44 UTC
I am experiencing a recurring issue with the QField Android app when connecting to my self-hosted QFieldCloud instance. The problem surfaced after I pulled the latest changes from the QFieldCloud GitHub repositories and deployed them to my local server instance yesterday.

Issue Description:
The QField Android app displays an error indicating that the SSL handshake was unsuccessful. The specific error message suggests that the app is unable to locate the certificate issuer for the locally found certificate.

Temporary Workaround:
I found that clearing the cache data from the QField app temporarily resolves the issue. However, this solution only works for a short period, and the problem reappears after 10 to 30 minutes.

Details:

QField App Version: [Specify version]
QFieldCloud Server: Self-hosted, recently updated with the latest changes from the official GitHub repositories.
Error Message: "SSL handshake failed: Could not find the certificate issuer of the locally found certificate."
I am unsure whether this issue is related to the recent update of the QFieldCloud server or the version of the QField app. I would greatly appreciate your assistance in diagnosing and resolving this issue.

Please let me know if you require any further information or logs from my server or the QField app to assist with troubleshooting.

Thank you for your support.

**Comment by EgidijusViko** [comment] 2024-05-30 10:23
From 3.20 I think it started because with 3.19 work okey, if you mean about QField app

**Comment by suricactus** [comment] 2024-05-30 11:12
I am afraid this is not an issue with QFieldCloud. It is either your certificate autority, or the OpenSSL library on QField.

**Comment by EgidijusViko** [comment] 2024-05-30 11:14
But still for me strange that older versions working. Until 3.20. Maybe can conntact to you provide some more info to look depper?

**Comment by suricactus** [comment] 2024-05-30 11:41
Feel free to contact us at sales@qfield.cloud .

**Comment by EgidijusViko** [comment] 2024-06-19 04:25
Okey investgating more. And now see that problem mostly regarding token which generating qfieldcloud. 
Because in application I see in first try it try connect via saved token and then get this error.
On main screen see this error: [HTTP/0]https://domain.com/api/v1/auth/token Network error. Something with files. With Qfield.cloud same issue can't repeat because it each time ask for new token and not using old one which is saved.

**Comment by EgidijusViko** [comment] 2024-06-19 04:25
Okey investgating more. And now see that problem mostly regarding token which generating qfieldcloud. 
Because in application I see in first try it try connect via saved token and then get this error.
On main screen see this error: [HTTP/0]https://domain.com/api/v1/auth/token Network error. Something with files. With Qfield.cloud same issue can't repeat because it each time ask for new token and not using old one which is saved.

**Comment by EgidijusViko** [comment] 2024-06-26 09:47
Still exist this issue. Checked version release notes but nothing found about ssl checking and etc. Maybe any news?

**Comment by suricactus** [comment] 2024-06-26 12:29
We do not experience any SSL issues on any of our deployments, and you have confirmed that the issue is not present on app.qfield.cloud. There are no other bug reports on this matter. It seems the issue is on your setup, please contact us at sales@qfield.cloud to discuss your support contract options.
Closing this ticket.

**Closed** 2024-06-26 12:29 UTC
