### ISSUE TITLE
Reverse for 'project_overview' not found. 'project_overview' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by yeison8921** [opengisch/qfieldcloud#933] opened 2024-04-18 16:33 UTC
Hello 

When i try to use the option "View on site" on project view the following error occurs:

![imagen](https://github.com/opengisch/qfieldcloud/assets/20236022/5f549359-61bf-48c0-acfa-d208857fd320)

![imagen](https://github.com/opengisch/qfieldcloud/assets/20236022/fccbc75e-b1ee-4856-88ac-2a2931e6ffea)

I checked the documentacion, but i'm not able to find anything related to this issue.

**Comment by suricactus** [comment] 2024-05-15 15:16
Duplicate of #842

**Closed by suricactus** 2024-05-15 15:16 UTC
