### ISSUE TITLE
Layer without geometry suddenly shown as empty after synchronising via QFieldCloud

### ISSUE THREAD

**Issue by mottensmann** [opengisch/qfieldcloud#876] opened 2024-02-05 16:12 UTC
Since a few days I am experiencing a unexpected behaviour when synchronising `QField` projects via `QFieldCloud`. Any non-geometric layer is shown as empty, making it impossible to retrieve any data. The error only occurs when projects are synchronised via `QFieldCloud`, whereas a simple copy-paste transfer via a USB-cable works just fine. Displaying the project in `QGIS` (version 3.28.11) is fine as well. Assessing the affected gpkg files via app.qfield.cloud reveals that the data is existing there, supposing the problem occurs once the dataset is processed for or within QField (?).

I  am experiencing the problem on a Galaxy TabActive2 (android 9) and Galaxy S20+ (android 13), both using `QField` 3.34.1. 

I appreciate any comments and hints for a possible solution!

**Comment by BoswachterMarc** [comment] 2024-02-05 17:06
Related with #874 ?!

**Comment by mottensmann** [comment] 2024-02-05 18:05
Indeed, #874 sounds very similar. It seems there is a general problem with any layer that is non-spatial.

**Comment by guibeatle** [comment] 2024-02-05 21:02
I posted on #874 a possible solution.. It seems to be related with "Packaging Offliner" option on "Project settings" at QFieldCloud.

**Comment by suricactus** [comment] 2024-02-06 08:17
Hey! The problematic piece of code has been detected. Fix is being implemented. Will keep you updated.

**Comment by suricactus** [comment] 2024-02-06 08:17
Duplicate of https://github.com/opengisch/qfieldcloud/issues/874#issuecomment-1928956242

**Closed** 2024-02-06 08:18 UTC
