### ISSUE TITLE
Delta cannot be applied TypeError

### ISSUE THREAD

**Issue by miili** [opengisch/qfieldcloud#552] opened 2023-03-12 21:41 UTC
I have many deltas which fail with

```
15:49:17.576 qfieldcloud.qgis.apply_deltas WARNING  The modified feature pk valued does not match "sourcePk" in the delta in "network_locations_0fff3a2e_5d55_407e_b1c2_5fc3a115f77e": sourcePk=201 modifiedFeaturePk=201
15:49:17.577 qfieldcloud.qgis.apply_deltas ERROR    An unknown error has been encountered while applying delta: 'NoneType' object has no attribute 'strip'
```

Latter one looks like it is an unhandled exception.

**Comment by suricactus** [comment] 2023-03-12 21:45
See https://github.com/opengisch/qfieldcloud/pull/549 . Duplicate of #551

**Closed by suricactus** 2023-03-12 21:45 UTC

**Comment by miili** [comment] 2023-03-12 21:52
Great! Is this deployed in production?
